<template>
  <div id="examine">
    <el-table
        :data="tableData"
        style="width: 100%"
        max-height="100vh">
        <el-table-column
        fixed
        prop="name"
        label="申请人"
        width="200">
        </el-table-column>
        <el-table-column
        prop="content"
        label="文案内容"
        width="250"
        align="center">
        </el-table-column>
        <el-table-column
        prop="date"
        label="申请时间"
        width="350"
        align="center">
        </el-table-column>
        <el-table-column
        fixed="right"
        label="操作"
        width="200"
        align="center">
        <template slot-scope="scope">
            <el-button
            @click.native.prevent="examine(scope.$index, tableData)"
            type="text"
            size="small">
            查看详情
            </el-button>
        </template>
        </el-table-column>
    </el-table>
    <el-dialog
        :title="this.dialogTitle"
        :visible.sync="dialogVisible1"
        width="30%"
        center>
        <div style="text-align:center; margin-bottom:5%">{{dialogText}}</div>
        <el-image
            style="width: 100%; height: 200px"
            :src="this.tableData[indexNow].img"
            fit="fill"></el-image>
        <span slot="footer" class="dialog-footer">
            <el-button @click="dialogVisible2 = true">驳 回</el-button>
            <el-button type="primary" @click="pass()">通 过</el-button>
        </span>
        <el-dialog
            width="30%"
            title="驳回理由"
            :visible.sync="dialogVisible2"
            append-to-body>
            <el-input
                type="textarea"
                :autosize="{ minRows: 12, maxRows: 15}"
                placeholder="请输入内容"
                v-model="reason">
            </el-input>
            <div id="btn">
                <el-button style="width:40%" type="info" round @click="reject()">驳回</el-button>
            </div>
        </el-dialog>
    </el-dialog>
  </div>
</template>

<script>
export default {
    methods: {
      examine(index, rows) {
        this.dialogVisible1 = true;
        this.dialogTitle = this.tableData[index].name
        this.dialogText = this.tableData[index].content
        this.indexNow = index
        console.log(index, rows)
      },
      reject() {
        console.log(this.indexNow)
        this.axios({
            method:'post',
            url:'/authority/rfc59fre',
            data: {
                reportReason: this.reason,
                taskIndex: this.tableData[this.indexNow].taskIndex,
                teamId: this.tableData[this.indexNow].id
            }
        })
        .then((response => {
            if(response.data.code == 200){
                this.dialogVisible2 = false 
                this.tableData.splice(this.indexNow, 1)
            }
        }))
        .catch((error) => {
            console.log(error)
        })
      },
      pass() {
        this.axios({
            method:'post',
            url:'/backend/submit/pass',
            data: {
                taskIndex: this.tableData[this.indexNow].taskIndex,
                teamId: this.tableData[this.indexNow].id
            }
        })
        .then((response => {
            if(response.data.code == 200){
                this.dialogVisible1 = false
                this.tableData.splice(this.indexNow, 1)
            }
        }))
        .catch((error) => {
            console.log(error)
        })
      }
    },
    data() {
      return {
        dialogVisible1: false,
        dialogVisible2: false,
        dialogTitle: '',
        dialogText: '',
        indexNow: 0,
        reason:'',
        tableData: [{
          id: -1,
          taskIndex: -1,
          date: '1145-14-19',
          name: '田所 浩二',
          content: '哼哼哼啊啊啊啊啊啊',
          img: ''
        },]
      }
    },
    mounted() {
        if(!localStorage.token){
            this.$router.replace('/login')
        }
        this.axios({
            method:'post',
            url:'/backend/info/work',
            data: {
                token: localStorage.token
            }
        })
        .then((response => {
            console.log(response.data.data)
            let info = new Object()
            info.id = response.data.data.teamId
            info.taskIndex = info.id = response.data.data.taskIndex
            info.name = response.data.data.teamName
            info.date = response.data.data.finish_date
            info.content = response.data.data.myDescription
            info.img = "data:image/jpeg;base64," + response.data.data.uploadLocation
            this.tableData.push(info)
        }))
        .catch((error) => {
            console.log(error)
        })
        let info = new Object()
        info.date = 114
        info.name = "514"
        info.content = 1919810
        info.img ="data:image/jpeg;base64," + "AAABAAEAQEAAAAEAIAAoQgAAFgAAACgAAABAAAAAgAAAAAEAIAAAAAAAAEIAACMuAAAjLgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADKyEQAysogJVszXGI/0awAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADKyawAystQAMrL/CVfN4xiP9P8Yj/S7GI/0RgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMrJGADKyvAAysv8AMrL/ADKy/wlXzeMYj/T/GI/0/xiP9PYYj/SdGI/0KAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAysigAMrKeADKy9gAysv8AMrL/ADKy/wAysv8JV83jGI/0/xiP9P8Yj/T/GI/0/xiP9OQYj/SAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAysoAAMrLkADKy/wAysv8AMrL/ADKy/wAysv8AMrL/CVfN4xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9NEYj/RXAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADKyVwAystEAMrL/ADKy/wAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wlXzeMYj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/hiP9LMYj/QzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMrIzADKyswAysv4AMrL/ADKy/wAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wAysv8JV83jGI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/08hiP9JUYj/QVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAyshYAMrKVADKy8wAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wAysv8AMrL/CVfN4xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/04BiP9HcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAysncAMrLgADKy/wAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wlXzeMYj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0yRiP9FAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADKyUAAysskAMrL/ADKy/wAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wAysv8JV83jGI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T7GI/0rBiP9C4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMrIuADKyrAAysvsAMrL/ADKy/wAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wAysv8AMrL/CVfN4xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/TuGI/0jRiP9BMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAyshMAMrKOADKy7gAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wlXzeMYj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/TaGI/0cAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAysnAAMrLaADKy/wAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wAysv8JV83jGI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/TBGI/0SwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADKySwAyssEAMrL/ADKy/wAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wAysv8AMrL/CVfN4xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9PgYj/SkGI/0KgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMrIqADKypAAysvgAMrL/ADKy/wAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wlXzeMYj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9OgYj/SGGI/0EQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMrIRADKyzQAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wAysv8AMrL/ADKy/xhtzPEztvDpIZ72+hiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9MEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMrKAADKy5AAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wAysv8AMrL/DVPA+jW17ONG3v/9Rt///0Xd//Q1wfvlHJX1/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/TQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAysigAMrKdADKy9gAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wAysv8FQLj/K57i5UXc/fRG3///Rt///0bf//9G3///Rt///0PZ/usutfnrGI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAyskYAMrK7ADKy/wAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wAysv8ihdfrQdP560bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///z/T/uUmqPj0GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9NAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAysmoAMrLUADKy/wAysv8AMrL/ADKy/wAysv8AMrL/ADKy/wAysv8AMrL/ADKy/xZnyvQ7xfPlRt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt//+TrJ/OIgnfb8GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/TQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADKyEQAysocAMrLpADKy/wAysv8AMrL/ADKy/wAysv8AMrL/DFC//DOw6uJG3v/5Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///RNz/8DO+++YblPX/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADKyKwAysqUAMrL4ADKy/wAysv8EPrf/KZjf50Ta/PBG3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Qtj+6Cyy+e8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9NAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADKyTAAyssIfftTvQND56Ebf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///PtH94yWm9/cYj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/TQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEbf/0ZG3/+7Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3v/4OMf74yCc9f4Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARt//KEbf/51G3//2Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9E3P7uMbv65xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9NAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARt//gEbf/+RG3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9C1/7oKKz47xiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/0/xiP9P8Yj/TQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABG3/9XRt//0Ubf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//08zv3jIZ/2+RiP9P8Yj/T/GI/0/xiP9P8Yj/T/GI/00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEbf/zNG3/+zRt///Ubf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0Xe//U2xPvkHJb1/xiP9P8Yj/T/GI/0/xiP9NAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARt//FUbf/5VG3//yRt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0Ta/u0wuPrpGI/0/xiP9P8Yj/TQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARt//d0bf/+BG3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0DV/uYoqfjyGI/00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACqqVY1Udns20bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///DrL/NQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA3Y0ATMKcL/try8HjR9/+/Ebf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt//7kbf/41G3/8TAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAN2NAEzdjQD/3Y0A/6upVfJZ1d/mRt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3//7Rt//q0bf/y4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADdjQBM3Y0A/92NAP/djQD/3Y0A/5C3gulP2vHtRt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3//JRt//UAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA3Y0ATN2NAP/djQD/3Y0A/92NAP/djQD/0ZQV/3rDp+RI3vz2Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf/+BG3/93AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAN2NAEzdjQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/vZ41+WbOyeNG3//+Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt//8kbf/5VG3/8VAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADdjQBM3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/pqtd71XW5elG3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3//9Rt//s0bf/zMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA3Y0ATN2NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/irqN50zc9e5G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3//RRt//VwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAN2NAEzdjQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/Gmij+dcax40fe/fhG3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0ra9e50p5LfslsAcQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADdjQBM3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP+ypEn3YdHS5Ebf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///R979+Ge3seOhcCj+slsA/7JbAP+yWwDCslsASwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA3Y0ATN2NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP+ZsnPuU9jp6Ebf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///WcfS45OASfeyWwD/slsA/7JbAP+yWwD/slsA/7JbAPiyWwClslsAKgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAN2NAEzdjQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/9OSEf+EvZbnStz38Ebf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0bf//9Q1OnogpZx77JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAOmyWwCHslsAEQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADdjQBM3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/8ObK/xvybriR9/++Ubf//9G3///Rt///0bf//9G3///Rt///0bf//9G3///Rt///0nb9/ByqZbnq2QR/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbANSyWwBqAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA3Y0ATN2NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/6+nT/Rc09nlRt///0bf//9G3///Rt///0bf//9G3///Rt7++WO7uuKfciv8slsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbALqyWwBGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAN2NAEzdjQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/5S1e+tQ2e3sRt///0bf//9G3///VszZ5ZGET/SyWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA9rJbAJyyWwAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADdjQBK3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/0pMU/3/An+VU0eLsfpp767JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA47JbAHgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAN2NAGrdjQDS3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/uGIA47JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbALmyWwBFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA3Y0AEd2NAIbdjQDo3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/7hiAOOyWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA0rJbAGoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA3Y0AKt2NAKTdjQD43Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP+4YgDjslsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwDoslsAhrJbABEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA3Y0AS92NAMLdjQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/uGIA47JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAPiyWwCkslsAKgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA3Y0AcN2NANrdjQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/7hiAOOyWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAMGyWwBLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADdjQAT3Y0Ajt2NAO7djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP+4YgDjslsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA2rJbAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADdjQAu3Y0ArN2NAPvdjQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/uGIA47JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwDuslsAjrJbABMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADdjQBQ3Y0Ayd2NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/7hiAOOyWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAPuyWwCsslsALgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADdjQB43Y0A4N2NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP+4YgDjslsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAMmyWwBQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAN2NABbdjQCV3Y0A892NAP/djQD/3Y0A/92NAP/djQD/3Y0A/92NAP/djQD/uGIA47JbAP+yWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwD/slsA4LJbAHcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAN2NADPdjQCz3Y0A/t2NAP/djQD/3Y0A/92NAP/djQD/3Y0A/7hiAOOyWwD/slsA/7JbAP+yWwD/slsA/7JbAP+yWwDzslsAlbJbABYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAN2NAFfdjQDR3Y0A/92NAP/djQD/3Y0A/92NAP+4YgDjslsA/7JbAP+yWwD/slsA/7JbAP6yWwCzslsAMwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAN2NAIDdjQDk3Y0A/92NAP/djQD/uGIA47JbAP+yWwD/slsA/7JbANGyWwBXAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA3Y0AKN2NAJ7djQD23Y0A/7hiAOOyWwD/slsA5LJbAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA3Y0ARt2NALy4YgDislsAnrJbACgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAxXEAQwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA///////////////8P/////////gP////////4AP///////+AAf///////wAAf//////8AAAf//////AAAAf/////wAAAA/////+AAAAA/////gAAAAA////4AAAAAA///+AAAAAAB///wAAAAAAB//8AAAAAAAB//AAAAAAAAB/4AAAAAAAAH/4AAAAAAAAf/wAAAAAAAB//wAAAAAAAH//wAAAAAAAf//gAAAAAAB///gAAAAAAH///gAAAAAAf//+AAAAAAB///gAAAAAAH//8AAAAAAAf//AAAAAAAB//wAAAAAAAH/8AAAAAAAAf/gAAAAAAAB/4AAAAAAAAH/gAAAAAAAAf+AAAAAAAAH/4AAAAAAAB//gAAAAAAAf/+AAAAAAAD//4AAAAAAA///gAAAAAAP//+AAAAAAB///4AAAAAAB///gAAAAAAB//+AAAAAAAB//4AAAAAAAD//gAAAAAAAD/+AAAAAAAAD/4AAAAAAAAH/wAAAAAAAAf/gAAAAAAAH//gAAAAAAA///gAAAAAAP///gAAAAAD////AAAAAA/////AAAAAH/////AAAAB//////AAAAf/////+AAAH//////+AAA///////+AAP///////+AD////////8A/////////8H/////////9///////////////8="
        this.tableData.push(info)
    }
  }
</script>

<style scoped>
    #examine {
        width: 100%;
        height: 100%;
    }
    #pic {
        width: 80%;
        height: 50%;
        background-image: url('http://git.sends.cc/uploads/-/system/appearance/favicon/1/favicon.ico');
    }
    #btn {
        width: 100%;
        display: flex;
        justify-content: center;
        align-items: flex-start;
        margin-top: 5%;
    }
</style>